In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense

In [2]:
dataset=pd.read_csv('/home/shivam/Downloads/bank-customer-churn-modeling/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x=dataset.drop(labels=['RowNumber','CustomerId','Surname','Exited'],axis=1)
y=dataset['Exited']

In [4]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [5]:
y.head()
#y.size

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
label1=LabelEncoder()
x['Geography']=label1.fit_transform(x['Geography'])

In [8]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [9]:
label2=LabelEncoder()
x['Gender']=label2.fit_transform(x['Gender'])

In [10]:
# x

In [28]:
#one hot encoding of geological data
#problem may create due to variable x if occur chnage to other variable
x=pd.get_dummies(x, drop_first=True, columns=['Geography'])

Feature standardization

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [30]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [31]:
x_train[0]

array([ 0.16958176, -1.09168714, -0.46460796,  0.00666099, -1.21571749,
        0.8095029 ,  0.64259497, -1.03227043,  1.10643166, -0.5698444 ,
        1.74309049])

# Fit model

In [32]:
model=Sequential()
model.add(Dense(X.shape[1],activation='relu',input_dim=X.shape[1]))
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [33]:
X.shape[1]

11

In [34]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
model.fit(x_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose=1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 3s 355us/sample - loss: 0.4496 - accuracy: 0.8133
Epoch 2/10
8000/8000 [==============================] - 2s 299us/sample - loss: 0.3938 - accuracy: 0.8378
Epoch 3/10
8000/8000 [==============================] - 2s 300us/sample - loss: 0.3609 - accuracy: 0.8546
Epoch 4/10
8000/8000 [==============================] - 2s 289us/sample - loss: 0.3505 - accuracy: 0.8554
Epoch 5/10
8000/8000 [==============================] - 2s 289us/sample - loss: 0.3455 - accuracy: 0.8583
Epoch 6/10
8000/8000 [==============================] - 2s 290us/sample - loss: 0.3411 - accuracy: 0.8605
Epoch 7/10
8000/8000 [==============================] - 2s 287us/sample - loss: 0.3394 - accuracy: 0.8581
Epoch 8/10
8000/8000 [==============================] - 2s 297us/sample - loss: 0.3362 - accuracy: 0.8626
Epoch 9/10
8000/8000 [==============================] - 2s 308us/sample - loss: 0.3351 - accuracy: 0.8633
Epoch 10/10
8000/8000 [=

In [36]:
y_pred=model.predict_classes(x_test)

In [37]:
y_pred[0:10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1]], dtype=int32)

In [39]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [40]:
model.evaluate(x_test,y_test.to_numpy())

2000/2000 [==============================] - 0s 122us/sample - loss: 0.3327 - accuracy: 0.8635


[0.33274120765924453, 0.8635]

In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[1536,   59],
       [ 214,  191]])

In [44]:
accuracy_score(y_test,y_pred)

0.8635